/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppMain: typeof import('./components/layout/AppMain.vue')['default']
    BarChart: typeof import('./components/Chart/BarChart.vue')['default']
    Breadcrumb: typeof import('./components/layout/Breadcrumb.vue')['default']
    Cascader: typeof import('./components/DynamicForm/components/Cascader.vue')['default']
    Checkbox: typeof import('./components/DynamicForm/components/Checkbox.vue')['default']
    DatePicker: typeof import('./components/DynamicForm/components/DatePicker.vue')['default']
    DynamicForm: typeof import('./components/DynamicForm/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Input: typeof import('./components/DynamicForm/components/Input.vue')['default']
    InputNumber: typeof import('./components/DynamicForm/components/InputNumber.vue')['default']
    Layout: typeof import('./components/layout/Layout.vue')['default']
    PieChart: typeof import('./components/Chart/PieChart.vue')['default']
    Radio: typeof import('./components/DynamicForm/components/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/DynamicForm/components/Select.vue')['default']
    SideBar: typeof import('./components/Sidebar/SideBar.vue')['default']
    SideBarItem: typeof import('./components/Sidebar/SideBarItem.vue')['default']
    Switch: typeof import('./components/DynamicForm/components/Switch.vue')['default']
    TextArea: typeof import('./components/DynamicForm/components/TextArea.vue')['default']
    TimePicker: typeof import('./components/DynamicForm/components/TimePicker.vue')['default']
    Uploader: typeof import('./components/DynamicForm/components/Uploader.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
